/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();

// you can add a icon to a html canvas. simply supply its element id and the weather you want to show.
skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
skycons.add("text1", Skycons.CLEAR_DAY);
skycons.add("text2", Skycons.CLOUDY);
skycons.add("text3", Skycons.RAIN);

// start all icons animation!
skycons.play();

// update a icon on  canvas by its id
skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);

function setIcon(text) {
    switch (text) {
        case "Sunny":
            return "CLEAR_DAY";
            break;
        case "Clear (night)":
            return "CLEAR_NIGHT";
            break;
        case "Partly Cloudy":
            return "PARTLY_CLOUDY_DAY";
            break;
        case "Cloudy":
            return "CLOUDY";
            break;
        case "Mostly Cloudy":
            return "CLOUDY";
            break;
        case "Rain":
            return "RAIN";
            break;
        case "Scattered Showers":
            return "RAIN";
            break;
        case "Showers":
            return "RAIN";
            break;
        case "Scattered Thunderstorms":
            return "RAIN";
            break;
        case "Thunderstorms":
            return "RAIN";
            break;
        case "Sleet":
            return "SLEET";
            break;
        case "Snow":
            return "SNOW";
            break;
        case "Windy":
            return "WIND";
            break;
        case "Breezy":
            return "WIND";
            break;
        case "Foggy":
            return "FOG";
            break;
    }
}

function getJsonUntilSuccess(url, callback) {
    $.getJSON(url, function(data) {
        if (data.query.results) { // if data.query.results exist , do the following action.
            callback(data);
        } else {
            // console.info("reloading : ", url);
            getJsonUntilSuccess(url, callback);
        }
    })
}

$(document).ready(function() {
    getJsonUntilSuccess('https://query.yahooapis.com/v1/public/yql?q=select * from weather.forecast ' +
        'where woeid in (select woeid from geo.places(1) where text="Taipei City") and u="c"&format=json',
        function(data) {
            var currentTemperature = data.query.results.channel.item.condition.temp;
            var currentDate = data.query.results.channel.item.condition.date.substring(5, 16);
            var currentText = data.query.results.channel.item.condition.text;

            $('.temperature').text(currentTemperature);
            $('.date').text(currentDate);
            $('.text').text(currentText);
            skycons.set("today", setIcon(currentText));

            var date = [3];
            var dayHigh = [3];
            var dayLow = [3];
            var text = [3];
            for (var i = 1; i < 4; i++) {
                date[i] = data.query.results.channel.item.forecast[i].date;
                $('#date' + i).text(date[i]);

                dayHigh[i] = data.query.results.channel.item.forecast[i].high;
                dayLow[i] = data.query.results.channel.item.forecast[i].low;
                $('#temp' + i).text(dayLow[i] + "-" + dayHigh[i]);

                text[i] = data.query.results.channel.item.forecast[i].text;
                skycons.set("text" + i, setIcon(text[i]));
            }

        })

});


var cityList = [22];
var cityTemp = [22];
$('button').on('click', function() {
    $('li').each(function(i, element) {
        cityList[i] = $(this).text();
        getJsonUntilSuccess('https://query.yahooapis.com/v1/public/yql?q=select * from weather.forecast ' +
                'where woeid in (select woeid from geo.places(1) where text="' + cityList[i] + '") and u="c"&format=json',
                function(data) {
                    cityTemp[i] = data.query.results.channel.item.condition.temp;
                    console.log(cityList[i] + "" + cityTemp[i]);
                    $('.listTemp' + i).text(cityTemp[i] + "℃");
                })
            // $('button').text($(this).text()+"℃");
    })

})


/*
Get value from Bootstrap dropdown menu
*/
$('#dropdown li').on('click', function() {
    var city = $(this).text();
    getJsonUntilSuccess('https://query.yahooapis.com/v1/public/yql?q=select * from weather.forecast ' +
        'where woeid in (select woeid from geo.places(1) where text="' + city + '") and u="c"&format=json',
        function(data) {
            console.log(data);
            var currentTemperature = data.query.results.channel.item.condition.temp;
            var currentDate = data.query.results.channel.item.condition.date.substring(5, 16);
            var currentText = data.query.results.channel.item.condition.text;

            $('.temperature').text(currentTemperature);
            $('.date').text(currentDate);
            $('.text').text(currentText);
            skycons.set("today", setIcon(currentText));

            var date = [3];
            var dayHigh = [3];
            var dayLow = [3];
            var text = [3];
            for (var i = 1; i < 4; i++) {
                date[i] = data.query.results.channel.item.forecast[i].date;
                $('#date' + i).text(date[i]);

                dayHigh[i] = data.query.results.channel.item.forecast[i].high;
                dayLow[i] = data.query.results.channel.item.forecast[i].low;
                $('#temp' + i).text(dayLow[i] + "-" + dayHigh[i]);

                text[i] = data.query.results.channel.item.forecast[i].text;
                skycons.set("text" + i, setIcon(text[i]));
            }
            $('button').text(city);
        });

});
